
library(fs)
list.files()
list.files(
  path = ".",
  recursive = TRUE,
  include.dirs = TRUE
)

dir_tree(".", recurse = 1)

setwd("C:/Users/PaintRock/OneDrive - Alabama A&M University/PaintRock RemoteSens/Spectral_Diversity")

# ============================================================
# Create Markdown Project Specification File
# ============================================================
md_text <- c(
  
  "# Research Objective and Analysis Specification for Codex Agent",
  "",
  "## Project Title",
  "",
  "**Evaluating Relationships Between Hyperspectral Spectral Heterogeneity and Phylogenetic Diversity in the Paint Rock Forest Dynamics Plot**",
  "",
  "## Purpose",
  "",
  "The purpose of this project is to quantify and evaluate relationships between remotely sensed spectral heterogeneity and field-derived biodiversity metrics within the Paint Rock Forest Dynamics Plot. Specifically, this research investigates whether variation in hyperspectral reflectance can serve as a proxy for phylogenetic diversity across multiple spatial scales.",
  "",
  "The Codex agent will assist in:",
  "",
  "- Reviewing and understanding existing R scripts.",
  "- Identifying dependencies, inputs, and outputs within the workflow.",
  "- Reproducing analyses in a transparent and documented manner.",
  "- Generating summary statistics, figures, tables, and model outputs.",
  "- Evaluating relationships between spectral heterogeneity metrics and biodiversity metrics.",
  "- Documenting assumptions, limitations, and potential sources of error.",
  "- Producing publication-ready outputs where possible.",
  "",
  "## Scientific Objectives",
  "",
  "### Objective 1: Quantify Spectral Heterogeneity",
  "",
  "Calculate spectral heterogeneity metrics from drone-acquired hyperspectral imagery using quadrat-based sampling approaches.",
  "",
  "**Primary metric:**",
  "",
  "- Spectral entropy derived from pairwise spectral angle distributions among sampled pixels.",
  "",
  "**Potential secondary metrics:**",
  "",
  "- Alpha hull of pixels in PCA space",
  "- Euclidean distance in PCA space",
  "",
  "**Questions:**",
  "",
  "- How does spectral heterogeneity vary across the study area?",
  "- How sensitive are estimates to spatial grain size and pixel selection procedures?",
  "",
  "### Objective 2: Quantify Biodiversity Metrics",
  "",
  "Generate spatially explicit biodiversity layers derived from forest census data.",
  "",
  "**Metrics include:**",
  "",
  "- Shannon diversity",
  "- Faith's phylogenetic diversity",
  "- Abundance-weighted Faith's phylogenetic diversity",
  "",
  "**Questions:**",
  "",
  "- How do biodiversity patterns vary spatially?",
  "- How do diversity estimates change across analysis scales?",
  "",
  "### Objective 3: Evaluate Spectral-Biodiversity Relationships",
  "",
  "Determine whether spectral heterogeneity is associated with biodiversity metrics.",
  "",
  "**Primary hypotheses:**",
  "",
  "- H1: Spectral heterogeneity increases with phylogenetic diversity.",
  "- H2: Relationships vary across spatial scales.",
  "- H3: Environmental variables explain additional variation beyond biodiversity metrics alone.",
  "",
  "**Expected analyses:**",
  "",
  "- Correlation analyses",
  "- Linear regression",
  "- Generalized linear models where appropriate",
  "- Spatial diagnostics",
  "- Model comparison and variance partitioning",
  "",
  "**Primary response variables:**",
  "",
  "- Spectral entropy and other spectral heterogeneity metrics",
  "",
  "**Primary predictor variables:**",
  "",
  "- Faith's phylogenetic diversity",
  "- Abundance-weighted Faith's phylogenetic diversity",
  "- Shannon diversity",
  "",
  "### Objective 4: Assess Environmental Drivers",
  "",
  "Investigate whether environmental variables contribute to unexplained variation in spectral heterogeneity.",
  "",
  "**Potential variables:**",
  "",
  "- Elevation",
  "- Topographic position",
  "- Additional raster products available for the study area",
  "",
  "**Questions:**",
  "",
  "- How much variation is explained by environmental factors?",
  "- Does phylogenetic diversity remain significant after environmental controls are included?",
  "",
  "### Objective 5: Evaluate Scale Dependence",
  "",
  "Assess whether relationships change with spatial grain.",
  "",
  "**Current analysis scales:**",
  "",
  "- 10 m quadrats",
  "- 20 m quadrats",
  "- 50 m quadrats",
  "",
  "**Questions:**",
  "",
  "- Which scale produces the strongest biodiversity-spectral relationship?",
  "- Are observed relationships consistent across scales?",
  "",
  "## Data Sources",
  "",
  "### Data Organization and Processing Structure",
  "",
  "#### Raw Spectral Data Location",
  "",
  "The raw hyperspectral imagery used in this analysis is stored in:",
  "",
  "- **HSI_NA_trimmed/**",
  "",
  "This directory contains raw hyperspectral raster files (ENVI format), including paired `.hdr` metadata files and associated auxiliary files. Example entries include:",
  "",
  "- raw_0_rd_rf_or",
  "- raw_11159_rd_rf_or",
  "- raw_11892_rd_rf_or",
  "",
  "Each file represents a spatially referenced hyperspectral cube used as the primary input for downstream spectral processing.",
  "",
  "---",
  "",
  "#### Spatial Partitioning Inputs (Quadrat Shapefiles)",
  "",
  "Spatial partitioning of hyperspectral data into analysis units is defined in:",
  "",
  "- **Quad_Scale_SHPs/**",
  "",
  "This directory contains shapefiles used to segment imagery into fixed spatial grains:",
  "",
  "- 10 m quadrats (PR_10m.shp)",
  "- 20 m quadrats (PR_20m.shp)",
  "- 50 m quadrats (PR_50m.shp)",
  "",
  "Each scale includes standard GIS components (.shp, .dbf, .prj, .shx) and optional KML exports.",
  "",
  "These shapefiles define the spatial sampling framework for all spectral and biodiversity aggregation procedures.",
  "",
  "---",
  "",
  "#### Quadrat-Based Spectral Processing Outputs",
  "",
  "Processed and partitioned spectral data are stored in:",
  "",
  "- **Quad_Spectra/**",
  "",
  "This directory contains quadrat-level spectral extractions and derived products organized by spatial scale (10 m, 20 m, 50 m). It includes multiple processing stages:",
  "",
  "- Raw quadrat spectra (10m/, 20m/, 50m/)",
  "- Spectral smoothing outputs (*_smoothed_5nm, 50m_RGB_smooth)",
  "- Resampled spectra (*_resampled_5nm)",
  "- RGB composites (20m_RGB, 50m_RGB)",
  "- Vegetation indices (*_VegIndex)",
  "",
  "These outputs represent the primary analytical dataset used for spectral heterogeneity calculations.",
  "",
  "---",
  "",
  "#### Quadrat Extraction Workflow (Scripts)",
  "",
  "A scripted workflow is used to partition raw hyperspectral imagery into quadrats using the shapefiles above. These scripts are located in:",
  "",
  "- **scripts/**",
  "",
  "Key processing stages include:",
  "",
  "- **1_Data Processing/** — partitions raw hyperspectral rasters into quadrat-based subsets using Quad_Scale_SHPs",
  "- **2_Indices Creation/** — generates vegetation indices and derived spectral products",
  "- **3_Analysis/** — performs statistical analysis linking spectral metrics to biodiversity",
  "- **auxilary/** — helper functions and utilities",
  "- **Outdated/** — deprecated or legacy workflows",
  "- **visuals/** — figure generation scripts",
  "",
  "The quadrat partitioning workflow produces the organized outputs stored in Quad_Spectra/, which serve as the input for downstream spectral heterogeneity and biodiversity analyses.",
  "",
  "###Script where quad partioning occurs: /scripts/1_Data Processing/HSI_quad_crop_refined.R",
  "",
  "---",
  "",
  "### Forest Census Data",
  "",
  "Contains:",
  "",
  "- Species identity",
  "- Tree coordinates",
  "- DBH",
  "- Canopy Position Index (CPI)",
  "- Tag identifiers",
  "",
  "**Filtered analysis population:**",
  "",
  "- CPI = 4 or 5 OR",
  "- DBH > 200 mm",
  "",
  "**Expected dataset size:**",
  "",
  "- Approximately 4,519 upper canopy individuals",
  "- Approximately 51 species",
  "",
  "### Hyperspectral Imagery",
  "",
  "**Sensor:**",
  "",
  "- Headwall Micro A-Series VNIR",
  "",
  "**Characteristics:**",
  "",
  "- 396–1002 nm spectral range",
  "- 328 bands",
  "- Approximately 2 nm spectral resolution",
  "- 10 cm spatial resolution",
  "",
  "**Derived products:**",
  "",
  "- Reflectance mosaics",
  "- Shadow masks",
  "- Spectral heterogeneity rasters",
  "",
  "## Codex Agent Responsibilities",
  "",
  "### Script Review",
  "",
  "For each R script:",
  "",
  "- Identify purpose.",
  "- List required packages.",
  "- Document inputs.",
  "- Document outputs.",
  "- Identify assumptions.",
  "- Identify computational bottlenecks.",
  "- Detect unused code or variables.",
  "- Include identification of whether inputs originate from raw hyperspectral data (HSI_NA_trimmed/) or pre-partitioned quadrat outputs (Quad_Spectra/).",
  "",
  "### Reproducibility",
  "",
  "The agent should:",
  "",
  "- Prefer modular functions.",
  "- Avoid hard-coded file paths.",
  "- Clearly document workflow dependencies.",
  "- Record package versions when possible.",
  "- Flag analyses that cannot be reproduced due to missing data.",
  "",
  "### Output Generation",
  "",
  "Produce:",
  "",
  "- Data tables (.CSV)",
  "- Summary tables",
  "- Regression summaries",
  "- Diagnostic plots",
  "- Spatial maps",
  "- Correlation matrices",
  "- Variable importance summaries",
  "",
  "All outputs should be saved using consistent naming conventions.",
  "",
  "## Expected Deliverables",
  "",
  "### Figures",
  "",
  "Potential figures include:",
  "",
  "- Study area map",
  "- Spectral heterogeneity maps",
  "- Biodiversity maps",
  "- Scale comparison figures",
  "- Spectral diversity versus phylogenetic diversity scatterplots",
  "- Environmental covariate maps",
  "- Model diagnostic plots",
  "",
  "### Tables",
  "",
  "Potential tables include:",
  "",
  "- Species composition summary",
  "- Diversity metric summary statistics",
  "- Correlation matrix",
  "- Model coefficient tables",
  "- Variance explained by predictor groups",
  "",
  "### Statistical Outputs",
  "",
  "Report:",
  "",
  "- Coefficients",
  "- Standard errors",
  "- Confidence intervals",
  "- R² values",
  "- Adjusted R² values",
  "- P-values",
  "- Model diagnostics",
  "",
  "## Success Criteria",
  "",
  "The analysis will be considered successful if:",
  "",
  "- All scripts execute reproducibly.",
  "- Spectral heterogeneity metrics are generated correctly.",
  "- Biodiversity metrics are reproduced from census data.",
  "- Relationships between spectral and biodiversity metrics are quantified.",
  "- Scale-dependent effects are evaluated.",
  "- Environmental influences are assessed.",
  "- Results are documented sufficiently for manuscript preparation and future replication.",
  "",
  "## Notes for Agent",
  "",
  "This project is exploratory but hypothesis-driven. Preference should be given to transparent, reproducible workflows over computational complexity. Any modifications to existing analytical methods should be clearly documented and justified. The agent should maintain a detailed record of assumptions, data transformations, filtering procedures, and statistical decisions throughout the workflow."
)

writeLines(md_text, "RESEARCH_OBJECTIVES.md")
##################################################################
"Quad_Values/Spectral_diversitySHPs"

##########################################################################

# "CODEX_AGENT_GUIDELINES.md

output_file <- "CODEX_AGENT_GUIDELINES.md"

md_text2 <- c(
  "#Governance Standards",
  "",
  "## Working Directory",
  "",
  "C:/Users/PaintRock/OneDrive - Alabama A&M University/PaintRock RemoteSens/Spectral_Diversity",
  "",
  "## Repository Discovery Requirements",
  "",
  "Before performing any work, the agent must create or update the following project inventories.",
  "",
  "### Directory Map",
  "",
  "**Location:**",
  "`/reports/directory_map.md`",
  "",
  "**Purpose:**",
  "Provide a complete hierarchical map of the repository structure.",
  "",
  "**Include:**",
  "- folders",
  "- scripts",
  "- functions",
  "- reports",
  "- outputs",
  "- tests",
  "- documentation",
  "",
  "**Format:**",
  "```text",
  "project_root/",
  "data/",
  "    raw/",
  "    intermediate/",
  "    processed/",
  "",
  "scripts/",
  "    01_ingest/",
  "    02_clean/",
  "    03_transform/",
  "",
  "outputs/",
  "",
  "reports/",
  "```",
  "",
  "Update whenever the repository structure changes.",
  "",
  "---",
  "",
  "### Data Dictionary",
  "",
  "**Location:**",
  "`/reports/data_dictionary.md`",
  "",
  "**Purpose:**",
  "Provide a living inventory of all datasets used in the project.",
  "",
  "#### For every dataset include:",
  "",
  "- Dataset Name",
  "- Description",
  "- Source Location",
  "- Row Count",
  "- Column Count",
  "- Primary Keys",
  "- Date Fields",
  "- Numeric Fields",
  "- Categorical Fields",
  "- Missing Value Summary",
  "- Last Updated",
  "",
  "#### For every variable include:",
  "",
  "| Variable | Type | Description |",
  "|----------|------|-------------|",
  "",
  "The agent should update the data dictionary whenever:",
  "",
  "- new datasets are introduced",
  "- schemas change",
  "- fields are added or removed",
  "",
  "---",
  "",
  "## Coding Style & Naming Conventions",
  "",
  "### Language",
  "",
  "Use R for all generated code unless explicitly instructed otherwise.",
  "",
  "Generated code should remain compatible with:",
  "",
  "`R 4.2.3`",
  "",
  "---",
  "",
  "### Style",
  "",
  "Use:",
  "",
  "- 2-space indentation",
  "- meaningful object names",
  "- modular functions",
  "- concise logic",
  "",
  "#### Requirements:",
  "",
  "- Keep functions focused on a single responsibility.",
  "- Prefer maintainable solutions over clever solutions.",
  "- Add comments where logic is not obvious.",
  "- Avoid deeply nested logic.",
  "- Avoid duplicated code.",
  "",
  "---",
  "",
  "### Naming Standards",
  "",
  "#### Functions",
  "",
  "`snake_case()`",
  "",
  "Examples:",
  "",
  "```r",
  "clean_customer_data()",
  "calculate_growth_rate()",
  "```",
  "",
  "#### Variables",
  "",
  "`snake_case`",
  "",
  "Examples:",
  "",
  "```r",
  "customer_count",
  "sales_total",
  "```",
  "",
  "#### Constants",
  "",
  "`UPPER_SNAKE_CASE`",
  "",
  "Examples:",
  "",
  "```r",
  "MAX_ITERATIONS",
  "DEFAULT_LOOKBACK_DAYS",
  "```",
  "",
  "#### Files",
  "",
  "`snake_case.R`",
  "",
  "Examples:",
  "",
  "```text",
  "clean_customer_data.R",
  "customer_summary_report.R",
  "```",
  "",
  "#### Directories",
  "",
  "`lowercase_snake_case`",
  "",
  "Examples:",
  "",
  "```text",
  "raw_data",
  "processed_data",
  "analysis_results",
  "```",
  "",
  "---",
  "",
  "## Execution Planning Requirements",
  "",
  "For complex requests, create an ExecPlan before making changes.",
  "",
  "An ExecPlan should contain:",
  "",
  "- Objective",
  "- Requested task",
  "- Files To Review",
  "- Relevant files",
  "- Proposed Changes",
  "- Expected modifications",
  "- Validation Plan",
  "- How correctness will be verified",
  "- Risks",
  "- Potential side effects",
  "",
  "**Store plans under:**",
  "",
  "`/reports/execution_plans/`",
  "",
  "**Naming:**",
  "",
  "`YYYYMMDD_HHMM_execplan.md`",
  "",
  "---",
  "",
  "## Testing Standards",
  "",
  "Testing is mandatory for:",
  "",
  "- new features",
  "- bug fixes",
  "- refactors affecting logic",
  "",
  "**Preferred framework:**",
  "",
  "`testthat`",
  "",
  "**Location:**",
  "",
  "`/tests`",
  "",
  "**Naming:**",
  "",
  "`test_feature_name.R`",
  "",
  "### Requirements",
  "",
  "- test normal conditions",
  "- test edge cases",
  "- test failure conditions",
  "- test missing data scenarios",
  "- test invalid inputs",
  "",
  "When behavior changes:",
  "",
  "- update existing tests",
  "- update documentation",
  "",
  "---",
  "",
  "## Documentation Requirements",
  "",
  "Documentation is considered part of task completion.",
  "",
  "Update documentation whenever:",
  "",
  "- workflows change",
  "- outputs change",
  "- assumptions change",
  "- dependencies change",
  "",
  "Documentation locations:",
  "",
  "- `/README.md`",
  "- `/reports/`",
  "- `/docs/`",
  "",
  "---",
  "",
  "## Rules",
  "",
  "The agent must not:",
  "",
  "1. Modify system paths.",
  "2. Modify system environment variables.",
  "3. Modify files outside repository boundaries.",
  "4. Commit code.",
  "5. Push code.",
  "6. Rebase branches.",
  "7. Delete files without approval.",
  "",
  "The agent may:",
  "",
  "- recommend Git commands",
  "- generate commit messages",
  "- generate release notes",
  "",
  "The user remains responsible for all Git actions.",
  "",
  "---",
  "",
  "## Repository Organization Rules",
  "",
  "- Autonomous experimentation: `/autoresearch`",
  "- Architecture notes: `/reports/architecture`",
  "- Historical summaries: `/reports/history`",
  "- Task reports: `/reports/tasks`",
  "- Execution plans: `/reports/execution_plans`",
  "- Validation reports: `/reports/validation`",
  "- Logs: `/logs`",
  "",
  "---",
  "",
  "## Agent Expectations",
  "",
  "### Before Making Changes",
  "",
  "1. Review relevant repository files.",
  "2. Understand current implementation.",
  "3. Review project_state.md.",
  "4. Review data_dictionary.md.",
  "5. Review directory_map.md.",
  "6. Create an ExecPlan when required.",
  "7. Identify dependencies.",
  "8. Confirm assumptions.",
  "",
  "### During Work",
  "",
  "1. Make minimal targeted changes.",
  "2. Preserve existing functionality.",
  "3. Update tests.",
  "4. Update documentation.",
  "5. Record actions performed.",
  "",
  "### After Work",
  "",
  "1. Validate outputs.",
  "2. Run tests.",
  "3. Update data dictionary if needed.",
  "4. Update directory map if needed.",
  "5. Create task report.",
  "6. Create validation report.",
  "7. Summarize work completed.",
  "",
  "---",
  "",
  "## Project State Tracking",
  "",
  "Maintain:",
  "",
  "`/reports/project_state.md`",
  "",
  "### Purpose",
  "",
  "Provide project continuity between agent sessions.",
  "",
  "### Required Sections",
  "",
  "- Current Objective",
  "- Active Research Questions",
  "- Completed Work",
  "- Pending Work",
  "- Known Issues",
  "- Technical Debt",
  "- Important Assumptions",
  "- Next Recommended Actions",
  "",
  "Update after every major task.",
  "",
  "---",
  "",
  "## Completion Checklist",
  "",
  "A task is not complete until all applicable items are complete.",
  "",
  "Checklist:",
  "",
  "- [ ] Objective completed",
  "- [ ] Code updated",
  "- [ ] Tests added or updated",
  "- [ ] Validation completed",
  "- [ ] Documentation updated",
  "- [ ] Data dictionary updated",
  "- [ ] Directory map updated",
  "- [ ] Project state updated",
  "- [ ] Task report created",
  "- [ ] Validation report created",
  "- [ ] Summary provided to user"
)

writeLines(md_text2, output_file)


